### ISSUE TITLE
Wait defined period for mining after a pending transaction arrives in the network (PoA, clique-period: 0)

### ISSUE THREAD

**Issue by TobiWo** [niksmac/ethereum-scripts#2]
Relevant script: mining-only-new-txs.js

I would need the above mentioned script with the following addition:

- transaction comes in
- timer/interval of defined period starts
- client(s) start to mine all pending transactions after defined period
- if there are no pending transactions, no mining will happen (the original functionality of the aforementioned script) 

I tried to update it with the admin.sleep() functionality but this thought was probably to easy because it doesn't work:

```
var miningThreads = 1
 var periodBeforeMiningStarts = 5

function checkWork() {
    if (eth.getBlock("pending").transactions.length > 0) {
        admin.sleep(periodBeforeMiningStarts);
        if (eth.mining) return;
        console.log("== Pending transactions! Mining...");
        miner.start(miningThreads);
    } else {
        miner.stop();
        console.log("== No transactions! Mining stopped.");
    }
}

eth.filter("latest", function(err, block) { checkWork(); });
eth.filter("pending", function(err, block) { checkWork(); });

checkWork();
```

Many thanks for your help.

**Comment by TobiWo** [comment]
I tried some stuff and found some interesting behavior. Can you reply to that:

1. I start geth with the `--preload` flag, like proposed in the [ethereum.stackexchange](https://ethereum.stackexchange.com/questions/3151/how-to-make-miner-to-mine-only-when-there-are-pending-transactions/3152?noredirect=1#comment81754_3152) post
* while submit transactions to the network they are mined instantly like it should
* when I add my changes (see above) it is mined instantly anyway
2. I start geth without the `--preload` flag and load the script within the console with `loadScript()`
* mining works only for the first transaction submitted to the network
* new transactions are pending forever until I load the script again with `loadScript()`
3. I start geth without `-- preload` and do not load the script anyway
* mining starts when new transactions submitted
* every new submission of a transaction starts mining

This implies to me that:
* your script is ignored by geth while using the `--preload` flag
* PoA in ethereum does indeed support instant mining out of the box
* a script need to be reloaded everytime I want to execute it

Maybe I'm totally wrong but this is what I observed while trying out some settings.

**Comment by TobiWo** [comment]
Addition to 2. of above:
* it seems that scripts are only running (while using `loadScript()`) when the console is active
* the problem I described above is because I'm leaving the console
* while staying within the console, the script works as it should

Do you know if it is possible to load a script permanently, even when I close the console? 
I know, this is totally out of scope of this issue but it is at least related to it. But maybe I should open a issue at geth itself or study the www for an answer (couldn't find anything satisfying until now)

**Comment by niksmac** [comment]
Okay, in that case you can use any terminal multiplexer like screen. Leave the screen window intact and it will run there.
Personally I use tmux.
